// import { TransactionCardProps } from "@/types/transactionCard";

// export const transactionData: TransactionCardProps[] = [
//   {
//     date: new Date("2024-07-25"),
//     price: 35099900,
//     pricePerSqFt: 1546,
//     location: "Wonderlust, Wonderland",
//     badges: ["Sale", "Villa", "Residential", "OffPlan"],
//     bedrooms: 3,
//     bathrooms: 2,
//     areaSize: 2456,
//   },
//   {
//     date: new Date("2024-08-01"),
//     price: 45000000,
//     pricePerSqFt: 1600,
//     location: "Mystic Hills, Dreamland",
//     badges: ["Rent", "Apartment", "Residential", "New"],
//     bedrooms: 4,
//     bathrooms: 3,
//     areaSize: 3000,
//   },
//   {
//     date: new Date("2024-08-15"),
//     price: 25000000,
//     pricePerSqFt: 1200,
//     location: "Sunnyvale, Utopia",
//     badges: ["Sale", "Townhouse", "Residential"],
//     bedrooms: 2,
//     bathrooms: 2,
//     areaSize: 1800,
//   },
//   {
//     date: new Date("2024-07-25"),
//     price: 35099900,
//     pricePerSqFt: 1546,
//     location: "Wonderlust, Wonderland",
//     badges: ["Sale", "Villa", "Residential", "OffPlan"],
//     bedrooms: 3,
//     bathrooms: 2,
//     areaSize: 2456,
//   },
//   {
//     date: new Date("2024-08-01"),
//     price: 45000000,
//     pricePerSqFt: 1600,
//     location: "Mystic Hills, Dreamland",
//     badges: ["Rent", "Apartment", "Residential", "New"],
//     bedrooms: 4,
//     bathrooms: 3,
//     areaSize: 3000,
//   },
//   {
//     date: new Date("2024-08-15"),
//     price: 25000000,
//     pricePerSqFt: 1200,
//     location: "Sunnyvale, Utopia",
//     badges: ["Sale", "Townhouse", "Residential"],
//     bedrooms: 2,
//     bathrooms: 2,
//     areaSize: 1800,
//   },
// ];
