import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import RootProvider from "./root-provider";
import Head from "next/head";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["greek"], display: "swap" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <meta charSet="utf-8" />
        <meta name="theme-color" content="#ff0000" />
      </Head>
      <body className={cn(inter.className, "select-none")}>
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  );
}
