import type { Metadata } from "next";
import "./globals.css";
import RootProvider from "./root-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  );
}
