import { Calculator } from "./types";

export const Calculators: Calculator[] = [
  {
    key: "sales_value_estimator",
    name: "Sales Value Estimator",
    description:
      "Estimate current property sales value based on market trends and attributes.",
    inputs: [
      {
        key: "property_selection",
        label: "Property Selector",
        type: "property_selector",
        is_mandatory: false,
      },
      {
        key: "usage_type",
        label: "Usage Type",
        type: "radio",
        options: ["Residential", "Commercial"],
        is_mandatory: true,
      },
      {
        key: "sale_type",
        label: "Sale Type",
        type: "radio",
        options: ["First Sale", "Resale"],
        is_mandatory: true,
      },
      {
        key: "choose_area",
        label: "Choose Area",
        type: "dropdown",
        source: "dxb_area_list",
        searchable: true,
        is_mandatory: true,
      },
      {
        key: "choose_developer",
        label: "Choose Developer",
        type: "dropdown",
        source: "dxb_dev_list",
        searchable: true,
        is_mandatory: false,
      },
      {
        key: "choose_project",
        label: "Choose Project",
        type: "dropdown",
        source: "dxb_project_list",
        searchable: true,
        is_mandatory: false,
      },
      {
        key: "property_type",
        label: "Property Type",
        type: "dropdown",
        options: ["Villa", "Apartment", "Penthouse", "Land"],
        is_mandatory: true,
      },
      {
        key: "property_area",
        label: "Property Area",
        type: "slider",
        min: 50,
        max: 10000,
        step: 10,
        default_value: 1000,
        is_mandatory: true,
      },
      {
        key: "no_of_bedrooms",
        label: "No. of Bedrooms",
        type: "dropdown",
        options: [1, 2, 3, 4, 5, "6+"],
        is_mandatory: true,
      },
    ],
    outputs: [
      {
        key: "estimated_sales_value",
        label: "Estimated Sales Value",
        type: "metric",
      },
      { key: "insights", label: "Insights", type: "insights" },
    ],
  },
  {
    key: "rental_value_estimator",
    name: "Rental Value Estimator",
    description:
      "Calculate the optimal rental price using property features and market benchmarks.",
    inputs: [
      {
        key: "property_selection",
        label: "Property Selector",
        type: "property_selector",
        is_mandatory: true,
      },
      {
        key: "usage_type",
        label: "Usage Type",
        type: "radio",
        options: ["Residential", "Commercial"],
        is_mandatory: true,
      },
      {
        key: "sale_type",
        label: "Sale Type",
        type: "radio",
        options: ["First Rental", "Renewal"],
        is_mandatory: true,
      },
      {
        key: "choose_area",
        label: "Choose Area",
        type: "dropdown",
        source: "dxb_area_list",
        searchable: true,
        is_mandatory: true,
      },
      {
        key: "choose_developer",
        label: "Choose Developer",
        type: "dropdown",
        source: "dxb_dev_list",
        searchable: true,
        is_mandatory: false,
      },
      {
        key: "choose_project",
        label: "Choose Project",
        type: "dropdown",
        source: "dxb_proj_list",
        searchable: true,
        is_mandatory: false,
      },
      {
        key: "property_type",
        label: "Property Type",
        type: "dropdown",
        options: ["Villa", "Apartment", "Penthouse", "Land"],
        is_mandatory: true,
      },
      {
        key: "property_area",
        label: "Property Area",
        type: "slider",
        min: 50,
        max: 10000,
        step: 10,
        default_value: 100,
        is_mandatory: true,
      },
      {
        key: "no_of_bedrooms",
        label: "No. of Bedrooms",
        type: "dropdown",
        options: [1, 2, 3, 4, 5, "6+"],
        is_mandatory: true,
      },
    ],
    outputs: [
      {
        key: "estimated_rental_value",
        label: "Estimated Rental Value",
        type: "metric",
      },
      { key: "insights", label: "Insights", type: "insights" },
    ],
  },
  {
    key: "mortgage_payment_calculator",
    name: "Mortgage Payment Calculator",
    description:
      "Calculate mortgage payments, rates, and affordability for property financing.",
    inputs: [
      {
        key: "property_price",
        label: "Property Price",
        type: "currency_text",
        is_mandatory: true,
        helper_text: "Enter the total property price.",
      },
      {
        key: "down_payment",
        label: "Down Payment",
        type: "currency_text",
        is_mandatory: true,
        helper_text: "Enter your down payment.",
      },
      {
        key: "interest_rate",
        label: "Interest Rate",
        type: "slider",
        min: 1,
        max: 10,
        step: 0.1,
        default_value: 4.5,
        is_mandatory: true,
        helper_text: "Select your interest rate.",
      },
      {
        key: "mortgage_duration",
        label: "Mortgage Duration",
        type: "slider",
        min: 1,
        max: 30,
        step: 1,
        default_value: 20,
        is_mandatory: true,
        helper_text: "Select mortgage duration (years).",
      },
    ],
    outputs: [
      {
        key: "emi",
        label: "EMI",
        type: "metric",
      },
      {
        key: "total_interest_monthly",
        label: "Total Interest Monthly",
        type: "metric",
      },
      {
        key: "total_principal_monthly",
        label: "Total Principal Monthly",
        type: "metric",
      },
      {
        key: "total_payment_breakup_pie",
        label: "Total Payment Breakup Pie",
        type: "pie_chart",
      },
      {
        key: "principal_loan_amount",
        label: "Principal Loan Amount",
        type: "metric",
      },
      {
        key: "total_interest",
        label: "Total Interest",
        type: "metric",
      },
      {
        key: "amortization_stacked_bar_chart",
        label: "Amortization Stacked Bar Chart",
        type: "stacked_bar_chart",
      },
      {
        key: "amortization_table",
        label: "Amortization Table",
        type: "table",
      },
      {
        key: "insight",
        label: "Insight",
        type: "insights",
      },
    ],
  },
  {
    key: "investment_roi_calculator",
    name: "Investment ROI Estimator",
    description:
      "Estimate property investment returns and future profitability for better decision-making.",
    inputs: [
      {
        key: "property_selection",
        label: "Property Selector",
        type: "property_selector",
        is_mandatory: true,
      },
      {
        key: "transaction_type",
        label: "Transaction Type",
        type: "dropdown",
        options: ["Cash", "Mortgage"],
        is_mandatory: true,
      },
      {
        key: "purchase_price",
        label: "Purchase Price",
        type: "currency_text",
        is_mandatory: true,
      },
      {
        key: "annual_rental_income",
        label: "Annual Rental Income",
        type: "currency_text",
        is_mandatory: true,
      },
      {
        key: "annual_appreciation_rate",
        label: "Annual Appreciation Rate",
        type: "slider",
        min: 0,
        max: 100,
        step: 1,
        default_value: 5,
        is_mandatory: true,
      },
      {
        key: "holding_period",
        label: "Holding Period",
        type: "slider",
        min: 1,
        max: 30,
        step: 1,
        default_value: 10,
        is_mandatory: true,
      },
      {
        key: "purchase_cost",
        label: "Purchase Cost",
        type: "currency_text",
        is_mandatory: true,
      },
      {
        key: "property_size",
        label: "Property Size",
        type: "value",
        is_mandatory: true,
      },
      {
        key: "service_charges_per_sqft",
        label: "Service Charges per Sqft",
        type: "currency_text",
        is_mandatory: true,
      },
      {
        key: "total_service_charge",
        label: "Total Service Charge",
        type: "currency_text",
        is_mandatory: true,
      },
      {
        key: "market_value",
        label: "Market Value",
        type: "currency_text",
        is_mandatory: true,
      },
    ],
    outputs: [
      {
        key: "annualized_roi",
        label: "Annualized ROI",
        type: "metric",
      },
      {
        key: "total_rental_income",
        label: "Total Rental Income",
        type: "metric",
      },
      {
        key: "total_appreciation",
        label: "Total Appreciation",
        type: "metric",
      },
      {
        key: "total_investment",
        label: "Total Investment",
        type: "metric",
      },
      {
        key: "insight",
        label: "Insight",
        type: "insights",
      },
    ],
  },
  {
    key: "rent_vs_buy_comparison_tool",
    name: "Rent vs Buy Comparison Tool",
    description:
      "Compare financial benefits of renting versus buying a property over time.",
    inputs: [
      {
        key: "comfortable_home_price",
        label: "Comfortable Home Price",
        type: "currency_text",
        is_mandatory: true,
      },
      {
        key: "down_payment",
        label: "Down Payment",
        type: "currency_text",
        is_mandatory: true,
      },
      {
        key: "comfortable_monthly_rent",
        label: "Comfortable Monthly Rent",
        type: "currency_text",
        is_mandatory: true,
      },
      {
        key: "rent_duration",
        label: "Rent Duration (Years)",
        type: "slider",
        min: 1,
        max: 50,
        step: 1,
        default_value: 5,
        is_mandatory: true,
      },
      {
        key: "mortgage_rate",
        label: "Mortgage Rate (%)",
        type: "slider",
        min: 3,
        max: 10,
        step: 0.1,
        default_value: 5,
        is_mandatory: true,
      },
    ],
    outputs: [
      {
        key: "rent_vs_buy_chart",
        label: "Rent vs Buy Chart",
        type: "stacked_bar_chart",
      },
      {
        key: "monthly_payment_comparison_chart",
        label: "Monthly Payment Comparison Chart",
        type: "bar_chart",
      },
      {
        key: "total_payment_comparison_chart",
        label: "Total Payment Comparison Chart",
        type: "bar_chart",
      },
      {
        key: "insight",
        label: "Insight",
        type: "insights",
      },
    ],
  },
  {
    key: "home_affordability_calculator",
    name: "Home Affordability Calculator",
    description:
      "Assess the budget and affordability of purchasing a property based on finances.",
    inputs: [
      {
        key: "annual_income",
        label: "Annual Income",
        type: "currency_text",
        is_mandatory: true,
      },
      {
        key: "monthly_debts",
        label: "Monthly Debts",
        type: "currency_text",
        is_mandatory: true,
      },
      {
        key: "monthly_expenses",
        label: "Monthly Expenses",
        type: "currency_text",
        is_mandatory: true,
      },
      {
        key: "monthly_income",
        label: "Monthly Income",
        type: "auto_computed",
        is_mandatory: true,
      },
      {
        key: "monthly_expense",
        label: "Monthly Expense",
        type: "auto_computed",
        is_mandatory: true,
      },
      {
        key: "available_monthly_savings",
        label: "Available Monthly Savings",
        type: "auto_computed",
        is_mandatory: true,
      },
      {
        key: "savings_allocation",
        label: "Savings Allocation (%)",
        type: "slider",
        min: 0,
        max: 100,
        step: 1,
        default_value: 50,
        is_mandatory: true,
      },
      {
        key: "down_payment",
        label: "Down Payment",
        type: "currency_text",
        is_mandatory: true,
      },
      {
        key: "mortgage_duration",
        label: "Mortgage Duration (Years)",
        type: "slider",
        min: 1,
        max: 30,
        step: 1,
        default_value: 20,
        is_mandatory: true,
      },
    ],
    outputs: [
      {
        key: "affordable_property_value",
        label: "Affordable Property Value",
        type: "metric",
      },
      {
        key: "down_payment",
        label: "Down Payment",
        type: "metric",
      },
      {
        key: "total_loan_amount",
        label: "Total Loan Amount",
        type: "metric",
      },
      {
        key: "current_savings",
        label: "Current Savings",
        type: "metric",
      },
      {
        key: "current_expenses",
        label: "Current Expenses",
        type: "metric",
      },
      {
        key: "savings_after_mortgage",
        label: "Savings After Mortgage",
        type: "metric",
      },
      {
        key: "insight",
        label: "Insight",
        type: "insights",
      },
    ],
  },
];
