export const schema = [
  {
    name: { transactionNumber: "TRANSACTION_NUMBER" },
    mode: "NULLABLE",
    type: "STRING",
    description: "A unique identifier for each transaction.",
    fields: [],
  },
  {
    name: { procedureId: "PROCEDURE_ID" },
    mode: "NULLABLE",
    type: "INTEGER",
    description:
      "Unique identifier for the procedure associated with the transaction.",
    fields: [],
  },
  {
    name: { groupId: "GROUP_ID" },
    mode: "NULLABLE",
    type: "INTEGER",
    description: "Identifier for the group associated with the transaction.",
    fields: [],
  },
  {
    name: { groupAr: "GROUP_AR" },
    mode: "NULLABLE",
    type: "STRING",
    description: "Arabic name of the group associated with the transaction.",
    fields: [],
  },
  {
    name: { groupEn: "GROUP_EN" },
    mode: "NULLABLE",
    type: "STRING",
    description: "English name of the group associated with the transaction.",
    fields: [],
  },
  {
    name: { procedureAr: "PROCEDURE_AR" },
    mode: "NULLABLE",
    type: "STRING",
    description:
      "Arabic name of the procedure associated with the transaction.",
    fields: [],
  },
  {
    name: { procedureEn: "PROCEDURE_EN" },
    mode: "NULLABLE",
    type: "STRING",
    description:
      "English name of the procedure associated with the transaction.",
    fields: [],
  },
  {
    name: { instanceDate: "INSTANCE_DATE" },
    mode: "NULLABLE",
    type: "DATE",
    description: "Date when the transaction or procedure took place.",
    fields: [],
  },
  {
    name: { propertyTypeId: "PROPERTY_TYPE_ID" },
    mode: "NULLABLE",
    type: "INTEGER",
    description:
      "Unique identifier for the type of property involved in the transaction.",
    fields: [],
  },
  {
    name: { propTypeAr: "PROP_TYPE_AR" },
    mode: "NULLABLE",
    type: "STRING",
    description: "Arabic name of the property type.",
    fields: [],
  },
  {
    name: { propTypeEn: "PROP_TYPE_EN" },
    mode: "NULLABLE",
    type: "STRING",
    description: "English name of the property type.",
    fields: [],
  },
  {
    name: { propertySubTypeId: "PROPERTY_SUB_TYPE_ID" },
    mode: "NULLABLE",
    type: "FLOAT",
    description:
      "Unique identifier for the sub-type of property involved in the transaction.",
    fields: [],
  },
  {
    name: { propSbTypeAr: "PROP_SB_TYPE_AR" },
    mode: "NULLABLE",
    type: "STRING",
    description: "Arabic name of the property sub-type.",
    fields: [],
  },
  {
    name: { propSbTypeEn: "PROP_SB_TYPE_EN" },
    mode: "NULLABLE",
    type: "STRING",
    description: "English name of the property sub-type.",
    fields: [],
  },
  {
    name: { usageAr: "USAGE_AR" },
    mode: "NULLABLE",
    type: "STRING",
    description: "Arabic description of the property usage.",
    fields: [],
  },
  {
    name: { usageEn: "USAGE_EN" },
    mode: "NULLABLE",
    type: "STRING",
    description: "English description of the property usage.",
    fields: [],
  },
  {
    name: { isOffPlan: "IS_OFFPLAN" },
    mode: "NULLABLE",
    type: "INTEGER",
    description: "Indicator if the property is off-plan.",
    fields: [],
  },
  {
    name: { isOffPlanAr: "IS_OFFPLAN_AR" },
    mode: "NULLABLE",
    type: "STRING",
    description: "Arabic description of whether the property is off-plan.",
    fields: [],
  },
  {
    name: { isOffPlanEn: "IS_OFFPLAN_EN" },
    mode: "NULLABLE",
    type: "STRING",
    description: "English description of whether the property is off-plan.",
    fields: [],
  },
  {
    name: { areaId: "AREA_ID" },
    mode: "NULLABLE",
    type: "INTEGER",
    description:
      "Unique identifier for the area where the property is located.",
    fields: [],
  },
  {
    name: { areaAr: "AREA_AR" },
    mode: "NULLABLE",
    type: "STRING",
    description: "Arabic name of the area where the property is located.",
    fields: [],
  },
  {
    name: { areaEn: "AREA_EN" },
    mode: "NULLABLE",
    type: "STRING",
    description: "English name of the area where the property is located.",
    fields: [],
  },
  {
    name: { buildingNameAr: "building_name_ar" },
    mode: "NULLABLE",
    type: "STRING",
    description: "Arabic name of the building.",
    fields: [],
  },
  {
    name: { buildingNameEn: "building_name_en" },
    mode: "NULLABLE",
    type: "STRING",
    description: "English name of the building.",
    fields: [],
  },
  {
    name: { projectNumber: "project_number" },
    mode: "NULLABLE",
    type: "FLOAT",
    description: "Project number associated with the transaction.",
    fields: [],
  },
  {
    name: { projectAr: "PROJECT_AR" },
    mode: "NULLABLE",
    type: "STRING",
    description: "Arabic name of the project.",
    fields: [],
  },
  {
    name: { projectEn: "PROJECT_EN" },
    mode: "NULLABLE",
    type: "STRING",
    description: "English name of the project.",
    fields: [],
  },
  {
    name: { masterProjectEn: "master_project_en" },
    mode: "NULLABLE",
    type: "STRING",
    description: "English name of the master project.",
    fields: [],
  },
  {
    name: { masterProjectAr: "master_project_ar" },
    mode: "NULLABLE",
    type: "STRING",
    description: "Arabic name of the master project.",
    fields: [],
  },
  {
    name: { nearestLandmarkAr: "nearest_landmark_ar" },
    mode: "NULLABLE",
    type: "STRING",
    description: "Arabic name of the nearest landmark.",
    fields: [],
  },
  {
    name: { nearestLandmarkEn: "nearest_landmark_en" },
    mode: "NULLABLE",
    type: "STRING",
    description: "English name of the nearest landmark.",
    fields: [],
  },
  {
    name: { nearestMetroAr: "nearest_metro_ar" },
    mode: "NULLABLE",
    type: "STRING",
    description: "Arabic name of the nearest metro station.",
    fields: [],
  },
  {
    name: { nearestMetroEn: "nearest_metro_en" },
    mode: "NULLABLE",
    type: "STRING",
    description: "English name of the nearest metro station.",
    fields: [],
  },
  {
    name: { nearestMallAr: "nearest_mall_ar" },
    mode: "NULLABLE",
    type: "STRING",
    description: "Arabic name of the nearest mall.",
    fields: [],
  },
  {
    name: { nearestMallEn: "nearest_mall_en" },
    mode: "NULLABLE",
    type: "STRING",
    description: "English name of the nearest mall.",
    fields: [],
  },
  {
    name: { roomsAr: "ROOMS_AR" },
    mode: "NULLABLE",
    type: "STRING",
    description: "Arabic description of the number of rooms.",
    fields: [],
  },
  {
    name: { roomsEn: "ROOMS_EN" },
    mode: "NULLABLE",
    type: "STRING",
    description: "English description of the number of rooms.",
    fields: [],
  },
  {
    name: { hasParking: "has_parking" },
    mode: "NULLABLE",
    type: "INTEGER",
    description: "Indicator if the property has parking.",
    fields: [],
  },
  {
    name: { actualArea: "ACTUAL_AREA" },
    mode: "NULLABLE",
    type: "FLOAT",
    description: "Actual area of the property in square meters.",
    fields: [],
  },
  {
    name: { transValue: "TRANS_VALUE" },
    mode: "NULLABLE",
    type: "FLOAT",
    description: "Transaction value in the respective currency.",
    fields: [],
  },
  {
    name: { meterSalePrice: "meter_sale_price" },
    mode: "NULLABLE",
    type: "FLOAT",
    description: "Sale price per square meter.",
    fields: [],
  },
  {
    name: { rentValue: "rent_value" },
    mode: "NULLABLE",
    type: "FLOAT",
    description: "Rent value in the respective currency.",
    fields: [],
  },
  {
    name: { meterRentPrice: "meter_rent_price" },
    mode: "NULLABLE",
    type: "FLOAT",
    description: "Rent price per square meter.",
    fields: [],
  },
  {
    name: { noOfPartiesRole1: "no_of_parties_role_1" },
    mode: "NULLABLE",
    type: "FLOAT",
    description: "Number of parties involved with role 1.",
    fields: [],
  },
  {
    name: { noOfPartiesRole2: "no_of_parties_role_2" },
    mode: "NULLABLE",
    type: "FLOAT",
    description: "Number of parties involved with role 2.",
    fields: [],
  },
  {
    name: { noOfPartiesRole3: "no_of_parties_role_3" },
    mode: "NULLABLE",
    type: "FLOAT",
    description: "Number of parties involved with role 3.",
    fields: [],
  },
  {
    name: { isFreeHold: "IS_FREE_HOLD" },
    mode: "NULLABLE",
    type: "FLOAT",
    description: "Indicator if the property is freehold.",
    fields: [],
  },
  {
    name: { isFreeHoldEn: "IS_FREE_HOLD_EN" },
    mode: "NULLABLE",
    type: "STRING",
    description: "English description of the freehold status.",
    fields: [],
  },
  {
    name: { isFreeHoldAr: "IS_FREE_HOLD_AR" },
    mode: "NULLABLE",
    type: "STRING",
    description: "Arabic description of the freehold status.",
    fields: [],
  },
];
